from __future__ import annotations
import io
from types import TracebackType
from typing import Any

from ladle.io.core import Position, Region
from ladle.io.sam import Flags, Header, MappingQuality
import ladle.io.sam as sam

class Record:
    def name(self) -> bytes | None: ...
    def flags(self) -> Flags: ...
    def reference_sequence_id(self) -> int | None: ...
    def alignment_start(self) -> Position | None: ...
    def mapping_quality(self) -> MappingQuality | None: ...
    def cigar(self) -> bytes: ...
    def mate_reference_sequence_id(self) -> int | None: ...
    def mate_alignment_start(self) -> Position | None: ...
    def template_length(self) -> int: ...
    def sequence(self) -> bytes: ...
    def quality_scores(self) -> bytes: ...
    def data(self) -> dict[bytes, int | float | bytes | list[int] | list[float]]: ...
    def __repr__(self) -> str: ...

class Reader:
    @staticmethod
    def from_path(path: str) -> Reader: ...
    @staticmethod
    def from_fd(fd: io.RawIOBase) -> Reader: ...
    def read_header(self) -> Header: ...
    def records_to_batch(self) -> RecordBatch: ...
    def __iter__(self) -> Reader: ...
    def __next__(self) -> Record: ...
    def close(self) -> None: ...
    def __enter__(self) -> Reader: ...
    def __exit__(
        self,
        exc_type: type[BaseException] | None,
        exc_val: BaseException | None,
        exc_tb: TracebackType | None,
    ) -> None: ...
    def __repr__(self) -> str: ...

class Query:
    def __iter__(self) -> Query: ...
    def __next__(self) -> Record: ...
    def __len__(self) -> int: ...
    def __repr__(self) -> str: ...

class IndexedReader:
    @staticmethod
    def from_path(path: str) -> IndexedReader: ...
    def read_header(self) -> Header: ...
    def query(self, header: Header, region: Region) -> Query: ...
    def close(self) -> None: ...
    def __enter__(self) -> IndexedReader: ...
    def __exit__(
        self,
        exc_type: type[BaseException] | None,
        exc_val: BaseException | None,
        exc_tb: TracebackType | None,
    ) -> None: ...
    def __repr__(self) -> str: ...

class Writer:
    @staticmethod
    def from_path(path: str) -> Writer: ...
    def write_header(self, header: Header) -> None: ...
    def write_record(self, header: Header, record: Record) -> None: ...
    def write_sam_record(self, header: Header, record: sam.Record) -> None: ...
    def close(self) -> None: ...
    def __enter__(self) -> Writer: ...
    def __exit__(
        self,
        exc_type: type[BaseException] | None,
        exc_val: BaseException | None,
        exc_tb: TracebackType | None,
    ) -> None: ...
    def __repr__(self) -> str: ...

class RecordBatch:
    @staticmethod
    def from_arrow(batch: Any) -> RecordBatch: ...
    @staticmethod
    def from_polars(df: Any) -> RecordBatch: ...
    @staticmethod
    def from_pandas(df: Any) -> RecordBatch: ...
    def to_arrow(self) -> Any: ...
    def to_polars(self) -> Any: ...
    def to_pandas(self) -> Any: ...
    def to_iterator(self) -> RecordBatchIterator: ...
    def __len__(self) -> int: ...
    def __repr__(self) -> str: ...

class RecordBatchIterator:
    def __iter__(self) -> RecordBatchIterator: ...
    def __next__(self) -> Record: ...

class bai:
    class Index:
        @staticmethod
        def read_from_path(path: str) -> bai.Index: ...
        def __repr__(self) -> str: ...
