from __future__ import annotations
from types import TracebackType
from typing import Any

from ladle.io.core import Position, Region
from ladle.io.vcf import Header

class Record:
    def reference_sequence_name(self, header: Header) -> str: ...
    def variant_start(self) -> Position | None: ...
    def ids(self) -> list[str]: ...
    def reference_bases(self) -> bytes: ...
    def alternate_bases(self) -> list[str]: ...
    def quality_score(self) -> float | None: ...
    def filters(self, header: Header) -> list[str]: ...
    def info(self, header: Header) -> dict[str, int | float | bool | str | list[int | float | str | None] | None]: ...
    def __repr__(self) -> str: ...

class Reader:
    @staticmethod
    def from_path(path: str) -> Reader: ...
    def read_header(self) -> Header: ...
    def records_to_batch(self, header: Header) -> RecordBatch: ...
    def __iter__(self) -> Reader: ...
    def __next__(self) -> Record: ...
    def close(self) -> None: ...
    def __enter__(self) -> Reader: ...
    def __exit__(
        self,
        exc_type: type[BaseException] | None,
        exc_val: BaseException | None,
        exc_tb: TracebackType | None,
    ) -> None: ...
    def __repr__(self) -> str: ...

class RecordBatch:
    @staticmethod
    def from_arrow(batch: Any) -> RecordBatch: ...
    @staticmethod
    def from_polars(df: Any) -> RecordBatch: ...
    @staticmethod
    def from_pandas(df: Any) -> RecordBatch: ...
    def to_arrow(self) -> Any: ...
    def to_polars(self) -> Any: ...
    def to_pandas(self) -> Any: ...
    def to_iterator(self) -> RecordBatchIterator: ...
    def __len__(self) -> int: ...
    def __repr__(self) -> str: ...

class RecordBatchIterator:
    def __iter__(self) -> RecordBatchIterator: ...
    def __next__(self) -> Record: ...

class Query:
    def __iter__(self) -> Query: ...
    def __next__(self) -> Record: ...
    def __len__(self) -> int: ...
    def __repr__(self) -> str: ...

class IndexedReader:
    @staticmethod
    def from_path(path: str) -> IndexedReader: ...
    def read_header(self) -> Header: ...
    def query(self, header: Header, region: Region) -> Query: ...
    def close(self) -> None: ...
    def __enter__(self) -> IndexedReader: ...
    def __exit__(
        self,
        exc_type: type[BaseException] | None,
        exc_val: BaseException | None,
        exc_tb: TracebackType | None,
    ) -> None: ...
    def __repr__(self) -> str: ...

class Writer:
    @staticmethod
    def from_path(path: str) -> Writer: ...
    def write_header(self, header: Header) -> None: ...
    def write_record(self, header: Header, record: Record) -> None: ...
    def write_vcf_record(self, header: Header, record: "ladle.vcf.Record") -> None: ...
    def close(self) -> None: ...
    def __enter__(self) -> Writer: ...
    def __exit__(
        self,
        exc_type: type[BaseException] | None,
        exc_val: BaseException | None,
        exc_tb: TracebackType | None,
    ) -> None: ...
    def __repr__(self) -> str: ...
