from __future__ import annotations
from types import TracebackType

COMPRESSION_NONE: int
COMPRESSION_FAST: int
COMPRESSION_BEST: int

class VirtualPosition:
    MIN: VirtualPosition
    MAX: VirtualPosition

    def __new__(cls, compressed: int, uncompressed: int) -> VirtualPosition: ...
    @staticmethod
    def from_u64(n: int) -> VirtualPosition: ...
    def compressed(self) -> int: ...
    def uncompressed(self) -> int: ...
    def __int__(self) -> int: ...
    def __str__(self) -> str: ...
    def __repr__(self) -> str: ...
    def __hash__(self) -> int: ...
    def __eq__(self, other: object) -> bool: ...
    def __lt__(self, other: VirtualPosition) -> bool: ...
    def __le__(self, other: VirtualPosition) -> bool: ...
    def __gt__(self, other: VirtualPosition) -> bool: ...
    def __ge__(self, other: VirtualPosition) -> bool: ...

class Reader:
    @staticmethod
    def from_path(path: str) -> Reader: ...
    def read(self, size: int) -> bytes: ...
    def read_all(self) -> bytes: ...
    def read_line(self) -> bytes: ...
    def position(self) -> int: ...
    def virtual_position(self) -> VirtualPosition: ...
    def seek(self, vpos: VirtualPosition) -> VirtualPosition: ...
    def close(self) -> None: ...
    def __enter__(self) -> Reader: ...
    def __exit__(
        self,
        exc_type: type[BaseException] | None,
        exc_val: BaseException | None,
        exc_tb: TracebackType | None,
    ) -> None: ...
    def __repr__(self) -> str: ...

class Writer:
    @staticmethod
    def from_path(path: str, compression_level: int = 6) -> Writer: ...
    def write(self, data: bytes) -> int: ...
    def flush(self) -> None: ...
    def finish(self) -> None: ...
    def position(self) -> int: ...
    def virtual_position(self) -> VirtualPosition: ...
    def close(self) -> None: ...
    def __enter__(self) -> Writer: ...
    def __exit__(
        self,
        exc_type: type[BaseException] | None,
        exc_val: BaseException | None,
        exc_tb: TracebackType | None,
    ) -> None: ...
    def __repr__(self) -> str: ...

class gzi:
    class Index:
        @staticmethod
        def from_path(path: str) -> gzi.Index: ...
        def query(self, pos: int) -> VirtualPosition: ...
        def __len__(self) -> int: ...
        def __repr__(self) -> str: ...
