from __future__ import annotations

class Position:
    MIN: Position
    MAX: Position

    def __new__(cls, n: int) -> Position: ...
    def get(self) -> int: ...
    def checked_add(self, n: int) -> Position | None: ...
    @staticmethod
    def parse(s: str) -> Position: ...
    def __int__(self) -> int: ...
    def __str__(self) -> str: ...
    def __repr__(self) -> str: ...
    def __hash__(self) -> int: ...
    def __eq__(self, other: object) -> bool: ...
    def __lt__(self, other: Position) -> bool: ...
    def __le__(self, other: Position) -> bool: ...
    def __gt__(self, other: Position) -> bool: ...
    def __ge__(self, other: Position) -> bool: ...

class Interval:
    def __new__(
        cls,
        start: int | None = None,
        end: int | None = None,
    ) -> Interval: ...
    def start(self) -> Position | None: ...
    def end(self) -> Position | None: ...
    def contains(self, pos: Position) -> bool: ...
    def intersects(self, other: Interval) -> bool: ...
    @staticmethod
    def parse(s: str) -> Interval: ...
    def __str__(self) -> str: ...
    def __repr__(self) -> str: ...
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...

class Region:
    def __new__(cls, name: str | bytes, interval: Interval) -> Region: ...
    def name(self) -> bytes: ...
    def start(self) -> Position | None: ...
    def end(self) -> Position | None: ...
    def interval(self) -> Interval: ...
    @staticmethod
    def parse(s: str) -> Region: ...
    def __str__(self) -> str: ...
    def __repr__(self) -> str: ...
    def __eq__(self, other: object) -> bool: ...
