from __future__ import annotations

class Position:
    """1-based genomic position (minimum value is 1).

    Examples
    --------
    >>> pos = core.Position(100)
    >>> pos.get()
    100
    """

    MIN: Position
    MAX: Position

    def __new__(cls, n: int) -> Position:
        """Create a position from a 1-based integer. Raises ``ValueError`` if ``n < 1``."""
        ...
    def get(self) -> int:
        """Return the 1-based integer value."""
        ...
    def checked_add(self, n: int) -> Position | None:
        """Add ``n`` to the position, returning ``None`` on overflow."""
        ...
    @staticmethod
    def parse(s: str) -> Position:
        """Parse a position from its string representation."""
        ...
    def __int__(self) -> int: ...
    def __str__(self) -> str: ...
    def __repr__(self) -> str: ...
    def __hash__(self) -> int: ...
    def __eq__(self, other: object) -> bool: ...
    def __lt__(self, other: Position) -> bool: ...
    def __le__(self, other: Position) -> bool: ...
    def __gt__(self, other: Position) -> bool: ...
    def __ge__(self, other: Position) -> bool: ...

class Interval:
    """A 1-based, closed genomic interval ``[start, end]``.

    Both ``start`` and ``end`` are optional (``None`` means unbounded).

    Examples
    --------
    >>> iv = core.Interval(1, 1000)  # chr:1-1000
    >>> iv.contains(core.Position(500))
    True
    """

    def __new__(
        cls,
        start: int | None = None,
        end: int | None = None,
    ) -> Interval: ...
    def start(self) -> Position | None:
        """Inclusive start position, or ``None`` if unbounded."""
        ...
    def end(self) -> Position | None:
        """Inclusive end position, or ``None`` if unbounded."""
        ...
    def contains(self, pos: Position) -> bool:
        """Return ``True`` if *pos* falls within this interval."""
        ...
    def intersects(self, other: Interval) -> bool:
        """Return ``True`` if this interval overlaps *other*."""
        ...
    @staticmethod
    def parse(s: str) -> Interval:
        """Parse an interval from its string representation (e.g. ``"1-1000"``)."""
        ...
    def __str__(self) -> str: ...
    def __repr__(self) -> str: ...
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...

class Region:
    """A named genomic region: a reference sequence name plus an ``Interval``.

    Examples
    --------
    >>> region = core.Region(b"chr1", core.Interval(1, 1_000_000))
    >>> str(region)
    'chr1:1-1000000'
    """

    def __new__(cls, name: str | bytes, interval: Interval) -> Region: ...
    def name(self) -> bytes:
        """Reference sequence name as bytes."""
        ...
    def start(self) -> Position | None:
        """Inclusive start position of the region's interval, or ``None``."""
        ...
    def end(self) -> Position | None:
        """Inclusive end position of the region's interval, or ``None``."""
        ...
    def interval(self) -> Interval:
        """The underlying ``Interval`` of this region."""
        ...
    @staticmethod
    def parse(s: str) -> Region:
        """Parse a region from its string representation (e.g. ``"chr1:1-1000"``)."""
        ...
    def __str__(self) -> str: ...
    def __repr__(self) -> str: ...
    def __eq__(self, other: object) -> bool: ...
