from __future__ import annotations
from types import TracebackType

class Record:
    def name(self) -> bytes: ...
    def description(self) -> bytes | None: ...
    def sequence(self) -> bytes: ...
    def quality_scores(self) -> bytes: ...
    def __repr__(self) -> str: ...

class Reader:
    @staticmethod
    def from_path(path: str) -> Reader: ...
    @staticmethod
    def from_fd(file: object) -> Reader: ...
    def __iter__(self) -> Reader: ...
    def __next__(self) -> Record: ...
    def close(self) -> None: ...
    def __enter__(self) -> Reader: ...
    def __exit__(
        self,
        exc_type: type[BaseException] | None,
        exc_val: BaseException | None,
        exc_tb: TracebackType | None,
    ) -> None: ...
    def __repr__(self) -> str: ...

class Writer:
    @staticmethod
    def from_path(path: str) -> Writer: ...
    def write_record(self, record: Record) -> None: ...
    def close(self) -> None: ...
    def __enter__(self) -> Writer: ...
    def __exit__(
        self,
        exc_type: type[BaseException] | None,
        exc_val: BaseException | None,
        exc_tb: TracebackType | None,
    ) -> None: ...
    def __repr__(self) -> str: ...
