from __future__ import annotations
from types import TracebackType
from typing import Any

from ladle.io.core import Position

class Flags:
    SEGMENTED: int
    PROPERLY_SEGMENTED: int
    UNMAPPED: int
    MATE_UNMAPPED: int
    REVERSE_COMPLEMENTED: int
    MATE_REVERSE_COMPLEMENTED: int
    FIRST_SEGMENT: int
    LAST_SEGMENT: int
    SECONDARY: int
    QC_FAIL: int
    DUPLICATE: int
    SUPPLEMENTARY: int

    def __new__(cls, bits: int) -> Flags: ...
    def bits(self) -> int: ...
    def is_segmented(self) -> bool: ...
    def is_properly_segmented(self) -> bool: ...
    def is_unmapped(self) -> bool: ...
    def is_mate_unmapped(self) -> bool: ...
    def is_reverse_complemented(self) -> bool: ...
    def is_mate_reverse_complemented(self) -> bool: ...
    def is_first_segment(self) -> bool: ...
    def is_last_segment(self) -> bool: ...
    def is_secondary(self) -> bool: ...
    def is_qc_fail(self) -> bool: ...
    def is_duplicate(self) -> bool: ...
    def is_supplementary(self) -> bool: ...
    def __int__(self) -> int: ...
    def __repr__(self) -> str: ...
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...
    def __and__(self, other: Flags) -> Flags: ...
    def __or__(self, other: Flags) -> Flags: ...

class MappingQuality:
    MIN: MappingQuality
    MAX: MappingQuality

    def __new__(cls, n: int) -> MappingQuality: ...
    def get(self) -> int: ...
    def __int__(self) -> int: ...
    def __str__(self) -> str: ...
    def __repr__(self) -> str: ...
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...
    def __lt__(self, other: MappingQuality) -> bool: ...
    def __le__(self, other: MappingQuality) -> bool: ...
    def __gt__(self, other: MappingQuality) -> bool: ...
    def __ge__(self, other: MappingQuality) -> bool: ...

class Header:
    def __new__(cls) -> Header: ...
    @staticmethod
    def parse(s: str) -> Header: ...
    def reference_sequences(self) -> dict[bytes, int]: ...
    def __str__(self) -> str: ...
    def __repr__(self) -> str: ...

class Record:
    def name(self) -> bytes | None: ...
    def flags(self) -> Flags: ...
    def reference_sequence_name(self) -> bytes | None: ...
    def alignment_start(self) -> Position | None: ...
    def mapping_quality(self) -> MappingQuality | None: ...
    def cigar(self) -> bytes: ...
    def mate_reference_sequence_name(self) -> bytes | None: ...
    def mate_alignment_start(self) -> Position | None: ...
    def template_length(self) -> int: ...
    def sequence(self) -> bytes: ...
    def quality_scores(self) -> bytes: ...
    def data(self) -> dict[bytes, int | float | bytes | list[int] | list[float]]: ...
    def __repr__(self) -> str: ...

class Reader:
    @staticmethod
    def from_path(path: str) -> Reader: ...
    def read_header(self) -> Header: ...
    def records_to_batch(self) -> RecordBatch: ...
    def __iter__(self) -> Reader: ...
    def __next__(self) -> Record: ...
    def close(self) -> None: ...
    def __enter__(self) -> Reader: ...
    def __exit__(
        self,
        exc_type: type[BaseException] | None,
        exc_val: BaseException | None,
        exc_tb: TracebackType | None,
    ) -> None: ...
    def __repr__(self) -> str: ...

class RecordBatch:
    @staticmethod
    def from_arrow(batch: Any) -> RecordBatch: ...
    @staticmethod
    def from_polars(df: Any) -> RecordBatch: ...
    @staticmethod
    def from_pandas(df: Any) -> RecordBatch: ...
    def to_arrow(self) -> Any: ...
    def to_polars(self) -> Any: ...
    def to_pandas(self) -> Any: ...
    def to_iterator(self) -> RecordBatchIterator: ...
    def __len__(self) -> int: ...
    def __repr__(self) -> str: ...

class RecordBatchIterator:
    def __iter__(self) -> RecordBatchIterator: ...
    def __next__(self) -> Record: ...

class Writer:
    @staticmethod
    def from_path(path: str) -> Writer: ...
    def write_header(self, header: Header) -> None: ...
    def write_record(self, header: Header, record: Record) -> None: ...
    def close(self) -> None: ...
    def __enter__(self) -> Writer: ...
    def __exit__(
        self,
        exc_type: type[BaseException] | None,
        exc_val: BaseException | None,
        exc_tb: TracebackType | None,
    ) -> None: ...
    def __repr__(self) -> str: ...
